Translation into Brazilian Portuguese and corrections to docs in English
yiisoft/yii-console pull request #202
Opened 2024-04-12 12:26 UTC by luizcmarin

Note the following:
- created folders according to the standard for documentation
- all links checked

2024-04-13 06:22 UTC, vjik requested changes

2024-04-13 06:22 UTC, vjik commented on psalm80.min.xml
This file not need.

2024-04-14 16:57 UTC, luizcmarin commented on psalm80.min.xml
When I did this I had the minify plugin activated 🤦

2024-04-22 20:53 UTC, samdark commented
See https://github.com/yiisoft/yii-console/actions/runs/8781505107/job/24093666268?pr=202

2024-04-22 20:54 UTC, samdark requested changes
Please check tests.

2024-04-24 17:53 UTC, merged